apiVersion: v1
kind: Pod
metadata:
  name: dbapp-fe
  labels:
    app: dbapp-fe
spec:
  containers:
  - name: dbapp-fe
    image: ands/fe:latest
    imagePullPolicy: Never
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dbapp-fe-svc
spec:
  type: NodePort
  selector:
    app: dbapp-fe
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
