#!/bin/bash -e

function waitForPod {
    echo "Waiting for $1"
    while [[ $(kubectl get pods -l app=$1 -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do  sleep 1; done
}

echo "Creating resources"

echo "Creating Redis cache"
kubectl create -f redis.yaml
waitForPod "redis"


echo "Creating Mongo DB"
kubectl create -f mongo.yaml
waitForPod "mongo"


echo "Creating Janus gatway"
kubectl create -f janus.yaml
waitForPod "janus-gateway"

echo "Creating WebSocket server"
kubectl create -f ws-server.yaml
waitForPod "wss"

echo "Ok!"