apiVersion: v1
kind: Service
metadata:
  name: wss-svc
spec:
  selector:
    app: wss
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
        
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wss-config
data:
  server.port: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wss
spec:
  selector:
    matchLabels:
      app: wss
  template:
    metadata:
      labels:
        app: wss
    spec:
      restartPolicy: Always
      containers:
        - image: aviot-websocket-server:1.0.0
          name: wss
          ports:
          - name: ws
            containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: wss-config
                  key: server.port

